export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export DOTFILES=$HOME/Development/dotfiles
export ANTIGEN_HOME=$HOME/.antigen
export EDITOR=vim
export NVM_LAZY_LOAD=true
# set default user so theme doesn't show it
export DEFAULT_USER=phil
