# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd beep extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# ALIASES
alias sz='source $HOME/.zshrc'
alias redot=$DOTFILES/os/setup.sh

# git
alias gb='git branch'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull --prune'
alias gs='git status -sb'
alias gsta='git stash'
alias gp='git push origin HEAD'

# antigen stuff
source $ANTIGEN_HOME/antigen.zsh

antigen use oh-my-zsh

antigen theme agnoster/agnoster-zsh-theme agnoster

antigen bundle zsh-users/zsh-syntax-highlighting

# nvm
antigen bundle lukechilds/zsh-nvm
antigen bundle lukechilds/zsh-better-npm-completion

# docker
antigen bundle docker
antigen bundle docker-compose

antigen apply

export NVM_DIR="$HOME/.nvm"
source $NVM_DIR/nvm.sh

# exports
export BREW_FILE=$DOTFILES/os/install/macos/brew.sh
export CASK_FILE=$DOTFILES/os/install/macos/brew-cask.sh
