# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory autocd beep extendedglob
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# antigen stuff
source $ANTIGEN_HOME/antigen.zsh

# gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

for file in $DOTFILES/system/* ; do
  [ -f "$file" ] && . "$file"
done

antigen use oh-my-zsh

antigen theme agnoster/agnoster-zsh-theme agnoster

antigen bundle zsh-users/zsh-syntax-highlighting

# nvm
antigen bundle lukechilds/zsh-nvm
antigen bundle lukechilds/zsh-better-npm-completion

# docker
antigen bundle docker
antigen bundle docker-compose

antigen apply

# nvm stuff
export NVM_DIR="$HOME/.nvm"
source $NVM_DIR/nvm.sh

# ruby stuff
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# exports
export BREW_FILE=$DOTFILES/os/install/macos/brew.sh
export CASK_FILE=$DOTFILES/os/install/macos/brew-cask.sh
